#! /usr/bin/env python
# encoding: utf-8
# Juho Vähä-Herttua, 2008

import sys

def build(bld):
	obj = bld.new_task_gen('cc', 'staticlib')
	obj.source = ['taplog.c','tapcfg.c']
	obj.target = 'tapcfg'
	obj.name = 'tapcfg'
	obj.includes = '../include'
	obj.uselib = 'socket'

#	obj = bld.new_task_gen('cc', 'shlib')
#	obj.source = ['taplog.c','tapcfg.c']
#	obj.target = 'tapcfg'
#	obj.name = 'shtapcfg'
#	obj.includes = '../include'
#	obj.uselib = 'socket'
#	obj.lib = 'ws2_32'

