Import('env')

refpaths = ['.']

sources = Split("""
  EthernetDevice.cs
  EthernetFrame.cs
  """)

lib = env.CLILibrary('TAPCfg', sources)

sources = Split("""
  TAPCfgTest.cs
  """)

prog = env.CLIProgram('TAPCfgTest', sources, CILLIBS=lib)

