#! /usr/bin/env python
# encoding: utf-8
# Juho Vähä-Herttua, 2008

def build(bld):
	obj = bld.new_task_gen(features='cs')
	obj.source = ['EthernetDevice.cs']
	obj.target = 'EthernetDevice.exe'
	obj.uselib_local = 'shtapcfg'

