Import('env')

asm = env.CLILibrary('bindings/TAPCfg', ['bindings/EthernetDevice.cs','bindings/EthernetFrame.cs'])
prog = env.CLIProgram('bindings/TAPCfgTest', ['bindings/TAPCfgTest.cs'], CILLIBS=asm)

env.Append(CPPPATH = ['include'])
env.Library('lib/tapcfg', ['lib/tapcfg.c','lib/taplog.c'])
env.SharedLibrary('bindings/tapcfg', ['lib/tapcfg.c','lib/taplog.c'])

env.Append(LIBPATH = ['lib'])
object = env.Object('demos/listener.c')
prog1 = env.Program('demos/test_client', ['demos/test_client.c'], LIBS = ['tapcfg'], install=False)
prog2 = env.Program('demos/test_server', ['demos/listener.o','demos/test_server.c'], LIBS = ['tapcfg'], install=False)
prog3 = env.Program('demos/test_forwarder', ['demos/listener.o','demos/test_forwarder.c'], LIBS = ['tapcfg'], install=False)

