#! /usr/bin/env python
# encoding: utf-8
# Juho Vähä-Herttua, 2008

import sys

def build(bld):
	obj = bld.new_task_gen('cc', 'program')
	obj.source = ['test_client.c']
	obj.target = 'test_client'
	obj.uselib_local = 'tapcfg'
	obj.includes = '../include'
	obj.uselib = 'socket thread'

	obj = bld.new_task_gen('cc', 'program')
	obj.source = ['listener.c','test_server.c']
	obj.target = 'test_server'
	obj.uselib_local = 'tapcfg'
	obj.includes = '../include'
	obj.uselib = 'socket thread'

	obj = bld.new_task_gen('cc', 'program')
	obj.source = ['listener.c','test_forwarder.c']
	obj.target = 'test_forwarder'
	obj.uselib_local = 'tapcfg'
	obj.includes = '../include'
	obj.uselib = 'socket thread'

